---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: rocketchat
  namespace: rocketchat
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - rocketchat
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: rocket-chat
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: rocketchat
  name: rocketchat-subscription-1
  namespace: rocketchat
spec:
  channel: ggithubcom-likid0-dr-demo-ns/ggithubcom-likid0-dr-demo
  placement:
    placementRef:
      kind: PlacementRule
      name: rocketchat-placement
