apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: rocketchat
  namespace: rocketchat
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - rocketchat
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: metrodr
    apps.open-cluster-management.io/git-path: rocket-chat/manifests
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: rocketchat
  name: rocketchat-subscription-1
  namespace: rocketchat
spec:
  channel: ggithubcom-aplphago-dr-demo-ns/ggithubcom-aplphago-dr-demo
  placement:
    placementRef:
      kind: Placement
      name: rocketchat-placement-1
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  labels:
    app: rocketchat
  name: rocketchat-placement-1
  namespace: rocketchat
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'name'
              operator: 'In'
              values: 
                - 'spoke1'
  clusterSets:
    - global
